[log]
path = '/www/wwwlogs/python/callback_api/gunicorn_error.log'
level = 'info'
format = '%(asctime)s - %(name)s - %(levelname)s - %(message)s'

[proxy]
    [proxy.oauth]
    baidu='https://api2.hnzzzsw.com/oauth/baidu'
    douyin = 'https://api2.hnzzzsw.com/oauth/douyin'


[retry]
max_retry = 3
retry_delay = 1
